import { icon } from './icons.js';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const stageTips={
 product:{do:'Wybierz konkretny produkt albo rodzinę produktów. Zapisz zastosowanie, wariant i link do aktualnej karty.',example:'Taśma COB do światła pod szafkami. Model i długość instalacji do ustalenia z opiekunem produktu.',ready:'Jest jasne, co pokazujemy. Parametry i zdjęcia dotyczą tego samego wariantu.'},
 audience:{do:'Opisz jedną grupę: jej zadanie, potrzebę i rolę w wyborze produktu. Inny przekaz dla kolejnej grupy rozpisz w osobnej gałęzi.',example:'Stolarze wykonujący kuchnie na wymiar. Potrzebują detalu montażu profilu i listy elementów do zabudowy.',ready:'Potrafisz powiedzieć, dlaczego ta osoba zainteresuje się reklamą.'},
 message:{do:'Zapisz jedną korzyść i sposób jej pokazania. Użyj informacji potwierdzonych dla wybranego produktu.',example:'Pokaż linię światła pod szafkami, a następnie detal profilu w zabudowie.',ready:'Reklama ma jeden główny komunikat, a zdjęcie lub materiał go potwierdza.'},
 channel:{do:'Podaj miejsce emisji, cel i założenia odbiorców. Dla różnych kanałów dodaj osobne etapy.',example:'Meta Ads: inspiracja wnętrzem. Google Ads: odpowiedź na szukaną nazwę lub zastosowanie produktu.',ready:'Wiadomo, gdzie trafi kreacja. Ten etap zapisuje plan; reklamy uruchamia osoba obsługująca konto reklamowe.'},
 creative:{do:'Jeden etap = jeden materiał lub wariant do wykonania. W „Briefie dla grafika” wpisz rozmiar, dokładne teksty i wskazówki wizualne.',example:'Wariant A: gotowe wnętrze. Wariant B: detal montażu. Przy porównaniu zachowaj ten sam cel i odbiorcę.',ready:'Grafik zna format, teksty, materiały źródłowe, termin i osobę zbierającą uwagi.'},
 landing:{do:'Wklej docelowy adres i zapisz, co ma zobaczyć osoba po kliknięciu. Sprawdź stronę także na telefonie.',example:'Reklama profilu do mebli prowadzi do odpowiedniego profilu, jego wariantów i danych do montażu.',ready:'Produkt, obietnica i przycisk na stronie odpowiadają reklamie.'},
 conversion:{do:'Wybierz jedno działanie klienta. Zapisz, co dzieje się po formularzu, zakupie lub pobraniu.',example:'Zapytanie o dobór → potwierdzenie dla klienta → sprawa trafia do wskazanego opiekuna.',ready:'Działanie zostało przetestowane, a osoba obsługująca wie, co robić dalej.'},
 remarketing:{do:'Zapisz, do kogo wracamy, po jakim czasie i z jaką nową informacją. Ustal też wykluczenia.',example:'Osoba obejrzała profil, ale nie zapytała o dobór. Pokaż jej detal montażu lub dokumentację.',ready:'Kolejny materiał odpowiada na wątpliwość, a reguły emisji są ustalone z prowadzącym reklamy.'},
 measurement:{do:'Ustal, co mierzy sukces: np. wartościowe zapytania. Zapisz cel, źródło danych i datę przeglądu.',example:'Po pierwszym okresie porównaj liczbę zapytań z oceną handlowców: czy dotyczyły oferty i prowadziły do rozmów?',ready:'Jest konkretna decyzja: co zostawić, co poprawić, kto to zrobi i do kiedy.'},
};
export function stageHelpHTML(type,goal,nodeId){
 const tip=stageTips[type];if(!tip)return '';
 return `<details class="stage-help"><summary>${icon('note')} Jak uzupełnić ten etap? ${icon('chevronDown')}</summary><div><p>${tip.do}</p><span>PRZYKŁAD ROBOCZY</span><p class="tip-example">${tip.example}</p><span>KIEDY UZNAĆ ZA GOTOWE</span><p>${tip.ready}</p>${type==='creative'?`<a href="#handoff/${goal}/${esc(nodeId)}">Otwórz brief dla tej kreacji ${icon('arrow')}</a>`:`<a href="#guide/${goal}/map">Zobacz obsługę mapy ${icon('arrow')}</a>`}</div></details>`;
}
export const feedbackTemplate='Kreacja / nazwa pliku:\nWersja:\nCo zmienić:\nDokładny tekst po zmianie:\nCo zostaje bez zmian:\nOsoba potwierdzająca uwagi:\nTermin kolejnej wersji:';
const ownerSteps=[
 ['plan','Ustal produkt i cel','W „Briefie i zadaniach” opisz ofertę, odbiorców, potwierdzony wyróżnik i budżet. Wybierz, czy kampania ma prowadzić do zakupu, zapytania, konsultacji czy katalogu.','Przykład: profile do mebli → stolarze → zapytanie o dobór do projektu.','plan','Uzupełnij brief'],
 ['map','Ułóż drogę klienta','Na mapie przejdź od produktu do odbiorcy i przekazu. Następnie dopasuj kanał, materiał, stronę i działanie klienta. Zostaw gałęzie, które rzeczywiście chcesz przygotować.','Połączenia pokazują kolejność i warianty. Nie uruchamiają emisji reklam.','map','Przejdź do mapy'],
 ['play','Rozpisz materiały dla grafika','Nazwij każdą kreację, np. „Profile · detal montażu · wariant A”. W briefie dla grafika wybierz materiały do przekazania i wpisz dokładne teksty, format oraz wskazówki wizualne.','Jeśli porównujesz dwa pomysły, utwórz dwie kreacje. Łatwiej wtedy wskazać uwagi do konkretnego pliku.','handoff','Przygotuj zlecenie'],
 ['download','Przekaż brief i pliki źródłowe','Sprawdź podgląd dla grafika. Pobierz HTML lub zapisz go jako PDF. Dołącz folder z logo, zdjęciami, kartami produktów i ustalonym sposobem oddania projektów.','Pobrany HTML otwiera się na komputerze grafika w zwykłej przeglądarce. Link do folderu wymaga dostępu dla tej osoby.','handoff','Otwórz brief dla grafika'],
 ['check','Zbierz uwagi i sprawdź ścieżkę','Jedna osoba po stronie Prescot zbiera poprawki. Po akceptacji kreacji sprawdź teksty, wariant produktu, adres strony i działanie formularza lub zakupu.','Status „Gotowe” ustawiaj po wykonaniu i sprawdzeniu elementu. Status etapu mapy i szczegółowa checklista są zapisywane osobno.','report','Przejrzyj kampanię'],
 ['chart','Uruchom reklamy i wróć do wyników','Osoba prowadząca reklamy wdraża ustalenia na właściwym koncie. Po ustalonym okresie wpisz wyniki i wnioski w etapie „Pomiar”.','Zapisz też jakość zapytań od handlowców. Następna zmiana powinna wynikać z konkretnego wniosku.','area','Otwórz zadania pomiaru','measure'],
];
function ownerGuide(goal){return `<div class="guide-two-columns"><section class="guide-steps">${ownerSteps.map(([symbol,title,text,example,page,cta,stage],i)=>`<article class="guide-step"><span class="guide-number">${String(i+1).padStart(2,'0')}</span><div><h2>${title}</h2><p>${text}</p><p class="guide-example">${example}</p><a href="#${page}/${goal}${stage?'/'+stage:''}" class="text-link">${cta} ${icon('arrow')}</a></div></article>`).join('')}</section><aside class="guide-side"><div class="guide-callout"><span class="eyebrow">PODZIAŁ PRACY</span><h3>Kto za co odpowiada?</h3><dl><dt>Prowadzący kampanię</dt><dd>Produkt, odbiorcy, cel, treści, budżet i zebranie uwag.</dd><dt>Grafik / studio</dt><dd>Kompozycja, wersje projektu i eksporty według briefu.</dd><dt>Osoba od reklam</dt><dd>Ustawienia emisji, pomiar oraz ocena wyników z zespołem.</dd></dl></div><div class="guide-callout guide-orange"><span class="eyebrow">NA PIERWSZY RAZ</span><h3>Zacznij od jednej ścieżki.</h3><p>Jeden produkt, jedna grupa odbiorców i jasno opisany następny krok wystarczą, żeby przygotować pierwszy brief. Kolejne warianty dodasz na mapie.</p><a class="text-link" href="#map/${goal}">Otwórz swoją kampanię ${icon('arrow')}</a></div></aside></div>`;}
function designerGuide(goal){return `<div class="guide-designer"><section class="guide-designer-intro"><span class="stage-icon orange">${icon('play')}</span><div><h2>Dostajesz zadanie do wykonania.</h2><p>W briefie znajdziesz produkt, odbiorcę, listę kreacji, dokładne teksty, formaty, materiały źródłowe i termin. Każdy materiał ma własną nazwę, żeby łatwo wskazać wersję i poprawki.</p></div><a class="button primary" href="#handoff/${goal}">Otwórz brief ${icon('arrow')}</a></section><div class="designer-steps">${[
 ['01','Przeczytaj zakres','Sprawdź, ile materiałów jest wybranych, jakie mają formaty i jaki produkt pokazują. „Do uzupełnienia” oznacza, że trzeba wrócić z pytaniem do prowadzącego.'],
 ['02','Sprawdź materiały','Otwórz folder z logo i zdjęciami. Zwróć uwagę na właściwy model produktu. Parametry i treści mają pochodzić z ustaleń Prescot.'],
 ['03','Pokaż pierwszą wersję','Przygotuj projekt według wskazówek i oznacz go nazwą kreacji oraz wersją. Przy wideo pokaż kolejność ujęć i napisy przed końcowym eksportem.'],
 ['04','Oddaj pliki po poprawkach','Zastosuj uwagi zebrane przez wskazaną osobę. Oddaj ustalone eksporty i pliki źródłowe do podanego folderu. Zapisz, która wersja jest końcowa.'],
 ].map(([n,title,text])=>`<article><span>${n}</span><h3>${title}</h3><p>${text}</p></article>`).join('')}</div><section class="feedback-guide"><div><span class="eyebrow">ŻEBY UNIKNĄĆ „TYLKO JESZCZE JEDNEJ ZMIANY”</span><h2>Jedna lista uwag do jednej wersji.</h2><p>Podaj nazwę pliku i wpisz dokładny tekst po zmianie. Osoba zbierająca uwagi rozstrzyga sprzeczne komentarze przed przekazaniem ich grafikowi.</p><button class="button secondary" data-action="copy-feedback">${icon('copy')} Skopiuj wzór uwag</button></div><pre id="feedbackTemplate">${feedbackTemplate}</pre></section></div>`;}
function mapGuide(goal){return `<div class="guide-map-layout"><section class="map-instructions">${[
 ['cursor','Otwórz etap','Kliknij kartę. Po prawej pojawią się ustalenia, osoba i termin. Rozwiń „Jak uzupełnić ten etap?”, żeby zobaczyć przykład.'],
 ['map','Przesuwaj i łącz','Przeciągnij kartę, aby ją przesunąć. Prawą kropkę połącz z lewą kropką kolejnego etapu. Możesz też kliknąć kolejno wyjście i wejście.'],
 ['plus','Dodaj wariant','Wybierz „Dodaj etap” lub otwórz istniejący etap i użyj „Duplikuj”. Nazwij wariant, zmień ustalenia i połącz go z właściwą ścieżką.'],
 ['fit','Zobacz resztę mapy','Przesuwaj puste tło, korzystaj z miniatury i przycisków + / −. „Pokaż całą mapę” obejmuje wszystkie etapy. Na telefonie przesuwasz mapę palcem.'],
 ['undo','Cofnij pomyłkę','Przyciski cofania są na dole mapy. Działa także ⌘Z / Ctrl+Z. Historia cofania dotyczy bieżącego otwarcia mapy; zapisane ustalenia pozostają po odświeżeniu.'],
 ['shield','Zachowaj kopię','Zapis działa w tej przeglądarce. W „Briefie i zadaniach” pobierzesz pełną kopię JSON. Do grafika przygotuj osobny brief produkcyjny.'],
 ].map(([i,title,text])=>`<article><span class="stage-icon teal">${icon(i)}</span><div><h3>${title}</h3><p>${text}</p></div></article>`).join('')}</section><aside class="guide-callout"><span class="eyebrow">STATUSY I ZAPIS</span><h3>Co oznaczają liczby?</h3><dl><dt>Etapy przygotowane</dt><dd>Statusy kart na mapie, ustawiane przez Ciebie.</dd><dt>Zadania gotowe / 29</dt><dd>Szczegółowa checklista dla wybranego celu. Każdy cel ma własne notatki i statusy.</dd><dt>Zapis na tym urządzeniu</dt><dd>To dane tej przeglądarki. Na innym komputerze przenosisz je kopią JSON; wspólna edycja na żywo nie jest podłączona.</dd></dl><a href="#plan/${goal}" class="text-link">Brief i kopia zapisu ${icon('arrow')}</a></aside></div>`;}
export function guideView(goal,section='owner'){
 section=['owner','designer','map'].includes(section)?section:'owner';
 return `<section class="guide-heading"><div><span class="eyebrow">PORADNIK PRESCOT LED</span><h1>Od pomysłu do<br><span>briefu dla zespołu.</span></h1><p>Zobacz, co wpisać, komu przekazać zadanie i jak wrócić do wyników kampanii.</p></div><div class="guide-route" aria-label="Przebieg pracy"><span>${icon('diamond')} Produkt</span><i>→</i><span>${icon('users')} Odbiorca</span><i>→</i><span>${icon('play')} Kreacja</span><i>→</i><span>${icon('cursor')} Działanie</span></div></section><nav class="guide-tabs" aria-label="Części poradnika">${[['owner','plan','Prowadzę kampanię'],['designer','play','Przekazuję grafikowi'],['map','map','Obsługa mapy']].map(([id,symbol,title])=>`<a href="#guide/${goal}/${id}" ${id===section?'aria-current="page"':''} class="${id===section?'active':''}">${icon(symbol)}${title}</a>`).join('')}</nav>${({owner:ownerGuide,designer:designerGuide,map:mapGuide})[section](goal)}<section class="guide-faq"><h2>Przydatne odpowiedzi</h2>${[
 ['Co dokładnie wysłać grafikowi?','Pobierz brief HTML albo zapisz podgląd jako PDF. Dołącz dostęp do folderu z materiałami. Pobrany brief zawiera dane tej kampanii i wybrane kreacje; budżet reklamowy, checklista i inne kampanie nie są do niego dołączane.'],
 ['Czy wystarczy wysłać adres aplikacji?','Link otwiera aplikację, ale każda przeglądarka ma własne kampanie. Aby przekazać swoje ustalenia, wyślij grafikowi pobrany brief HTML lub PDF. HTML otworzy u siebie bez instalacji. To zapis ustaleń z chwili pobrania; po zmianach prześlij nową wersję pliku.'],
 ['Czy zdjęcia są dołączone do pobranego briefu?','Brief zawiera wpisane linki i nazwy plików. Same zdjęcia, logo i pliki projektowe udostępniasz w folderze lub dodajesz do wiadomości.'],
 ['Co robi przycisk AI?','Przygotowuje polecenie z kontekstem kampanii. Kopiujesz je do swojego narzędzia AI, sprawdzasz propozycję i przenosisz wybraną treść do ustaleń. Aplikacja nie wysyła polecenia do modelu automatycznie.'],
 ['Jak dobrać format kreacji?','W briefie dla grafika są przykładowe rozmiary robocze. Ustal miejsce emisji z osobą prowadzącą reklamy i wpisz właściwy rozmiar, typ pliku oraz — dla wideo — długość materiału.'],
 ].map(([q,a])=>`<details><summary>${q}${icon('chevronDown')}</summary><p>${a}</p></details>`).join('')}</section>`;
}
